apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-app-rh3
  title: sample-app-rh3
  annotations:
    janus-idp.io/tekton: sample-app-rh3
    tektonci/build-namespace: demo
    github.com/project-slug: piomin/sample-app-rh3
    sonarqube.org/project-key: piomin_sample-app-rh3
    backstage.io/kubernetes-id: sample-app-rh3
    argocd/app-name: sample-app-rh3
    prometheus.io/rule: container_memory_usage_bytes{pod=~"sample-app-rh3-.*"}|pod,rate(container_cpu_usage_seconds_total{pod=~"sample-app-rh3-.*"}[5m])|pod
  tags:
    - spring-boot
    - java
    - maven
    - tekton
    - argocd
    - renovate
    - sonarqube
spec:
  type: service
  owner: piomin
  lifecycle: experimental