apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: sample-app-rh3
build:
  artifacts:
    - image: piomin/sample-app-rh3
      jib:
        args:
          - -Pjib
          - -DskipTests
manifests:
  rawYaml:
    - k8s/deployment.yaml
deploy:
  kubectl: {}